In [1]:
import numpy as np # import library

In [2]:
x=np.array([0,1,2,3,4,5,6,7,8,9]) #x=np.arange(10) gives the same result but is faster

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [13]:
y=np.array([[12,5,2,4], [7,6,8,8], [1,6,7,7]])

In [14]:
y

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [15]:
y[0] # y[:,0] gives first column.  y[0,:] gives first row

array([12,  5,  2,  4])

In [29]:
y[:,0]

array([12,  7,  1])

In [30]:
y[0,:]

array([12,  5,  2,  4])

In [16]:
z=np.array([1,2,3,4,5,6,7,8,9])

In [17]:
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
z.shape

(9,)

In [27]:
z1=z.reshape(9,1)

z1 

In [28]:
z1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])