In [2]:
import numpy as np

In [3]:
payments = np.array([6.99, 12.40, 75, 1.55, 1, 2, 3, 2, 1, 5])

effectively the above is a list

In [6]:
print(payments)

[ 6.99 12.4  75.    1.55]


In [7]:
payments = np.array([6.99, 12.40, 75, 1.55, 1, 2, 3, 2, 1, 5])


In [8]:
print (payments)

[ 6.99 12.4  75.    1.55  1.    2.    3.    2.    1.    5.  ]


In [9]:
arr = np.array([1,3,5,7,9])

In [10]:
print(arr)

[1 3 5 7 9]


In [13]:
arr2 = np.array([[1,3,5,7,], [2,4,6,8]])

In [14]:
print(arr2)

[[1 3 5 7]
 [2 4 6 8]]


In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

shows number of rows and number of columns


In [17]:
arr2.dtype


dtype('int32')

32 bitinteger

In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

the rnage of intergers between 1 and 10 in increments of 2

In [19]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [23]:
arr2 = np.array([[1,3,5,7,], [2,4,6,8], [7,8,9,10]])

In [25]:
print(arr2)

[[ 1  3  5  7]
 [ 2  4  6  8]
 [ 7  8  9 10]]


In [26]:
arr3=arr2.reshape(4,3)

In [28]:
print(arr3)

[[ 1  3  5]
 [ 7  2  4]
 [ 6  8  7]
 [ 8  9 10]]


changes the shape of the matrices

In [29]:
payments

array([ 6.99, 12.4 , 75.  ,  1.55,  1.  ,  2.  ,  3.  ,  2.  ,  1.  ,
        5.  ])

In [30]:
transaction_fee = 1.00

In [31]:
payments-transaction_fee 

array([ 5.99, 11.4 , 74.  ,  0.55,  0.  ,  1.  ,  2.  ,  1.  ,  0.  ,
        4.  ])

doesn't update the original array.  for that we's need to tell it - 

In [34]:
updated_payments=payments-transaction_fee

In [35]:
updated_payments

array([ 5.99, 11.4 , 74.  ,  0.55,  0.  ,  1.  ,  2.  ,  1.  ,  0.  ,
        4.  ])

In [36]:
updated_payments

array([ 5.99, 11.4 , 74.  ,  0.55,  0.  ,  1.  ,  2.  ,  1.  ,  0.  ,
        4.  ])

typing up then hitting tab brings up all existing arrays

In [37]:
updated_payments>5

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [38]:
updated_payments<50

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [39]:
(updated_payments>5)| (updated_payments<50)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

The | is or.  & is and