In [1]:
import numpy as np

In [3]:
sequence = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
sequence

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#OR - 

In [7]:
sequence=np.arange(10) # does it for you but misses out the 10th entry (as per SQL)

In [8]:
sequence

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
matrix=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [12]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
matrix.shape # gives number of columns and rows

(3, 4)

In [14]:
matrix2=matrix.reshape(4,3)

In [15]:
matrix2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
list=np.arange(10)

In [17]:
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
list[0:6]

array([0, 1, 2, 3, 4, 5])

In [19]:
list[2:] # gives the third to the final entries 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
list[2:] # gives the third to the final entries 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
list[[0,5]] # returns the first and fifth entries

array([0, 5])

In [26]:
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
list.sum()

45

In [27]:
list.dtype

dtype('int32')

In [28]:
list.flatten

<function ndarray.flatten>

In [29]:
list.nonzero

<function ndarray.nonzero>

In [30]:
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
list.ravel

<function ndarray.ravel>

In [32]:
list.view

<function ndarray.view>

In [33]:
list.shape

(10,)

In [34]:
list2=list.reshape(10,1)

In [35]:
list2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
import pandas as pd
import numpy as np

In [38]:
df=pd.read_csv('iris_dataset.csv')

In [39]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [47]:
iris=df.to_numpy

In [48]:
iris

<bound method DataFrame.to_numpy of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1              

In [51]:
iris.ndim()

AttributeError: 'function' object has no attribute 'ndim'